### ISSUE TITLE
ERROR: dependency ‘feather’ is not available for package ‘tidyverse’

### ISSUE THREAD

**Issue by mdancho84** [tidyverse/tidyverse#32]
I'm trying to run Travis CI on a package that depends on `tidyverse`, and the build is failing with the following error:

ERROR: dependency ‘feather’ is not available for package ‘tidyverse’

**Comment by DavisVaughan** [comment]
@mdancho84 knowing that this came from `tidyquant`, I forked and tested it. Similar problem to:

#33 

and 

[from travis github](https://github.com/johnmyleswhite/ProjectTemplate/pull/149
)

There is a problem with feather where you need gcc-4.9, then for readxl you need to also specify CXX=g++-4.9. Beyond that, I don't know what all of it means.

Nevertheless, the following works as the travis.yml file:

```
language: r
warnings_are_errors: true
sudo: required
cache: packages

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

before_install: |
  mkdir ~/.R
  cat <<EOF > ~/.R/Makevars
  CXX1X=g++-4.9
  CXX1XSTD=-std=c++11
  CXX=gcc-4.9
```

[my travis test build](https://travis-ci.org/DavisVaughan/tidyquant/builds/194689767)
