### ISSUE TITLE
add working build settings for travis with packrat + tidyverse

### ISSUE THREAD

**Issue by maxheld83** [tidyverse/tidyverse#33]
I'm using the standard packrat settings for Travis (container based infrastructure), and I've run into some build problems stemming from `tidyverse` dependencies:

- [this](https://github.com/hadley/readxl/issues/176) for `readxl`, 
- and [this](https://github.com/wesm/feather/issues/154) for `feather`.

Both are related to C/C++ compiler dependencies if I understand the problem correctly.
I'm not sure whether they are related.

I thought I'd post this here because the `packrat` + `tidyverse` + Travis toolchain is perhaps commonly used.

I was also wondering whether it would be possible to publish/recommend a `.travis.yml` that we can rely on to work with the current version of tidyverse dependencies.

Figuring out these dependencies one-by-one is quite cumbersome for people not versed in compiler stuff (like myself), and this might (perhaps?) help **strengthen (technical) reproducibility** around the `tidyverse` toolchain, if it comes with *one* build environment.

Ps.: does this problem arise only when `packrat` is used, or are non-packrat setups used as well?

**Comment by maxheld83** [comment]
I actually now seem to have one `.travis.yml` that works without a hitch, and without any extra settings for all things `tidyverse`, but I am not sure whether it is recommended (since it relies on the yet beta-ish `trusty` container).

Anyway, this works, and is reasonably short. No `makevars` shenanigans necessary, apparently.

```
language: r

sudo: false

dist: trusty

install:
  - R -e "0" --args --bootstrap-packrat

warnings_are_errors: false

cache:
  packages: true
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
    - $TRAVIS_BUILD_DIR/packrat/

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

notifications:
  email: false
```
